import { Router, type IRouter } from "express";
import {
  ListWorkflowsResponse,
  GetWorkflowResponse,
  GetWorkflowParams,
} from "@workspace/api-zod";

const router: IRouter = Router();

const seedanceStyleMotionParams = (defaults: {
  prompt: string;
  motionPreset: string;
  strength: string;
  frames: string;
  aspect: string;
  grade: string;
}) => [
  {
    key: "source_image", label: "Reference Frame", type: "file",
    description: "The hero frame that every generated shot is anchored to",
    required: true, defaultValue: null, options: null, min: null, max: null, accept: "image/*",
  },
  {
    key: "prompt", label: "Shot Direction", type: "text",
    description: "Describe the action, performance, environment, and visual continuity",
    required: true, defaultValue: defaults.prompt, options: null, min: null, max: null, accept: null,
  },
  {
    key: "motion_preset", label: "Camera Path", type: "select",
    description: "The primary camera movement for this variation",
    required: false, defaultValue: defaults.motionPreset,
    options: ["zoom-in", "zoom-out", "pan-left", "pan-right", "tilt-up", "tilt-down", "rotate"],
    min: null, max: null, accept: null,
  },
  {
    key: "motion_strength", label: "Motion Energy", type: "slider",
    description: "How strongly the scene departs from the reference frame",
    required: false, defaultValue: defaults.strength, options: null, min: 10, max: 90, accept: null,
  },
  {
    key: "num_frames", label: "Clip Frames", type: "slider",
    description: "Longer clips take more GPU time",
    required: false, defaultValue: defaults.frames, options: null, min: 8, max: 64, accept: null,
  },
  {
    key: "aspect_ratio", label: "Delivery Frame", type: "select",
    description: "The composition used for the generated clip",
    required: false, defaultValue: defaults.aspect, options: ["16:9", "9:16", "1:1"], min: null, max: null, accept: null,
  },
  {
    key: "color_grade", label: "Color Direction", type: "select",
    description: "A controlled grade applied after animation",
    required: false, defaultValue: defaults.grade,
    options: ["teal-orange", "warm-vintage", "cold-thriller"], min: null, max: null, accept: null,
  },
];

// Built-in workflow templates — no DB needed, these are code-defined
const WORKFLOWS = [
  {
    id: "lip-sync-basic",
    name: "Lip Sync",
    description:
      "Animate a portrait photo to speak audio — upload a face image and an audio clip to generate a talking video.",
    category: "lip-sync",
    icon: "Mic",
    estimatedTime: "2-5 min",
    params: [
      {
        key: "face_image",
        label: "Face Image",
        type: "file",
        description: "A clear portrait photo (front-facing works best)",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "audio_file",
        label: "Audio File",
        type: "file",
        description: "The speech audio to sync (WAV or MP3)",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "audio/*",
      },
      {
        key: "expression_scale",
        label: "Expressiveness",
        type: "slider",
        description: "How much mouth and facial movement to add (0-100)",
        required: false,
        defaultValue: "50",
        options: null,
        min: 0,
        max: 100,
        accept: null,
      },
    ],
  },
  {
    id: "motion-control-animatediff",
    name: "Motion Control",
    description:
      "Add motion to a still image using AnimateDiff — control the movement style and intensity.",
    category: "motion-control",
    icon: "Zap",
    estimatedTime: "3-8 min",
    params: [
      {
        key: "source_image",
        label: "Source Image",
        type: "file",
        description: "The image to animate",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "motion_preset",
        label: "Motion Style",
        type: "select",
        description: "The type of movement to apply",
        required: true,
        defaultValue: "zoom-in",
        options: ["zoom-in", "zoom-out", "pan-left", "pan-right", "tilt-up", "tilt-down", "rotate"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "motion_strength",
        label: "Motion Strength",
        type: "slider",
        description: "How strong the motion effect is (0-100)",
        required: false,
        defaultValue: "50",
        options: null,
        min: 0,
        max: 100,
        accept: null,
      },
      {
        key: "num_frames",
        label: "Number of Frames",
        type: "slider",
        description: "How many frames to generate (16 = ~0.5s at 32fps)",
        required: false,
        defaultValue: "16",
        options: null,
        min: 8,
        max: 64,
        accept: null,
      },
      {
        key: "prompt",
        label: "Motion Prompt",
        type: "text",
        description: "Describe the motion in words (e.g. 'gentle camera pan across landscape')",
        required: false,
        defaultValue: "",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "video-generation-txt2vid",
    name: "Text to Video",
    description:
      "Generate a short video clip from a text description using video generation models.",
    category: "video-generation",
    icon: "Video",
    estimatedTime: "5-15 min",
    params: [
      {
        key: "prompt",
        label: "Video Prompt",
        type: "text",
        description: "Describe the video you want to create",
        required: true,
        defaultValue: "",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "negative_prompt",
        label: "Negative Prompt",
        type: "text",
        description: "What to avoid in the video",
        required: false,
        defaultValue: "blurry, low quality, watermark",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "width",
        label: "Width",
        type: "select",
        description: "Output video width",
        required: false,
        defaultValue: "512",
        options: ["256", "512", "768", "1024"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "height",
        label: "Height",
        type: "select",
        description: "Output video height",
        required: false,
        defaultValue: "512",
        options: ["256", "512", "768", "1024"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "num_frames",
        label: "Number of Frames",
        type: "slider",
        description: "Total frames in the output video",
        required: false,
        defaultValue: "24",
        options: null,
        min: 8,
        max: 80,
        accept: null,
      },
      {
        key: "steps",
        label: "Inference Steps",
        type: "slider",
        description: "More steps = higher quality but slower",
        required: false,
        defaultValue: "25",
        options: null,
        min: 10,
        max: 50,
        accept: null,
      },
    ],
  },
  // ─── Seedance-style local workflows ──────────────────────────
  // These mirror popular reference-led video workflows using the local,
  // user-owned AnimateDiff stack. They are intentionally not presented as
  // access to ByteDance Seedance or any proprietary hosted model.
  {
    id: "seedance-reference-motion",
    name: "Reference Motion",
    description: "Seedance-style local workflow: animate one hero image into a controlled reference-led shot.",
    category: "seedance-style",
    icon: "Sparkles",
    estimatedTime: "4-10 min",
    params: seedanceStyleMotionParams({
      prompt: "A fashion subject holds eye contact as fabric moves in a soft studio breeze, cinematic realism.",
      motionPreset: "zoom-in", strength: "42", frames: "24", aspect: "16:9", grade: "teal-orange",
    }),
  },
  {
    id: "seedance-camera-path",
    name: "Camera Path Shot",
    description: "Seedance-style local workflow: turn a keyframe into a dramatic dolly, orbit, or lateral camera move.",
    category: "seedance-style",
    icon: "Focus",
    estimatedTime: "4-10 min",
    params: seedanceStyleMotionParams({
      prompt: "A cinematic tracking shot with parallax depth, confident subject movement, precise production lighting.",
      motionPreset: "pan-right", strength: "55", frames: "32", aspect: "16:9", grade: "cold-thriller",
    }),
  },
  {
    id: "seedance-vertical-social",
    name: "Vertical Social Cut",
    description: "Seedance-style local workflow: create a polished 9:16 motion clip with space for social captions.",
    category: "seedance-style",
    icon: "Smartphone",
    estimatedTime: "4-10 min",
    params: seedanceStyleMotionParams({
      prompt: "A high-energy vertical campaign clip, subject centered with clean lower-third caption space, premium editorial motion.",
      motionPreset: "tilt-up", strength: "48", frames: "24", aspect: "9:16", grade: "warm-vintage",
    }),
  },
  {
    id: "seedance-product-reveal",
    name: "Product Reveal",
    description: "Seedance-style local workflow: bring a product keyframe to life with a clean reveal and controlled movement.",
    category: "seedance-style",
    icon: "PackageOpen",
    estimatedTime: "4-10 min",
    params: seedanceStyleMotionParams({
      prompt: "Premium product reveal, controlled hero lighting, slow camera push, crisp material detail, commercial finish.",
      motionPreset: "zoom-in", strength: "35", frames: "24", aspect: "1:1", grade: "teal-orange",
    }),
  },
  {
    id: "perform-anywhere-angles",
    name: "Perform Anywhere — Five Angles",
    description:
      "Combine your identity, wardrobe, location, pose, and prop references into five cinematic stills, then choose one for motion transfer.",
    category: "perform-anywhere",
    icon: "Camera",
    estimatedTime: "5-15 min",
    params: [
      {
        key: "identity_image",
        label: "Identity / Face Reference",
        type: "file",
        description: "A clear image of the performer",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "outfit_image",
        label: "Outfit Reference",
        type: "file",
        description: "The clothing you want the scene to carry over",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "location_image",
        label: "Location Reference",
        type: "file",
        description: "The environment or vehicle interior",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "pose_image",
        label: "Pose / Composition Reference",
        type: "file",
        description: "The framing and body position to preserve",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "prop_image",
        label: "Vehicle / Prop Reference",
        type: "file",
        description: "The car, object, or additional scene anchor",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "scene_prompt",
        label: "Scene Direction",
        type: "text",
        description: "Describe the performance scene and visual story",
        required: true,
        defaultValue: "cinematic performance scene, realistic environment, confident eye contact",
        options: null,
        min: null,
        max: 1000,
        accept: null,
      },
      {
        key: "motion_context",
        label: "Motion Context",
        type: "text",
        description: "A short prompt for the later animation stage",
        required: false,
        defaultValue: "a performer moving naturally inside the scene",
        options: null,
        min: null,
        max: 300,
        accept: null,
      },
    ],
  },
  {
    id: "modelark-seedance-reference-video",
    name: "Seedance Reference Video",
    description:
      "Create a hosted Seedance video from opening and closing frames, a reference clip, and reference audio. The visual and audio references guide one continuous generated result.",
    category: "video-generation",
    icon: "Clapperboard",
    estimatedTime: "1-5 min",
    params: [
      {
        key: "source_image",
        label: "Opening Frame",
        type: "file",
        description: "The image used to establish the first frame and visual identity",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "end_image",
        label: "Closing Frame",
        type: "file",
        description: "The target image for the final shot or freeze frame",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "source_video",
        label: "Reference Video",
        type: "file",
        description: "The framing, camera movement, or performance reference",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "video/*",
      },
      {
        key: "source_audio",
        label: "Reference Audio",
        type: "file",
        description: "Music, rhythm, or spoken timing that should guide the result",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "audio/*",
      },
      {
        key: "prompt",
        label: "Creative Direction",
        type: "text",
        description: "Describe the timeline, action, sound cues, transitions, and final frame",
        required: true,
        defaultValue:
          "Use the reference video framing throughout and the reference audio as the soundtrack. Begin on Image 1, follow the demonstrated action and camera movement, preserve product and subject identity, then resolve naturally into Image 2 as the final frame.",
        options: null,
        min: 1,
        max: 4000,
        accept: null,
      },
      {
        key: "ratio",
        label: "Aspect Ratio",
        type: "select",
        description: "The delivery frame for the generated video",
        required: false,
        defaultValue: "16:9",
        options: ["16:9", "9:16", "1:1"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "duration",
        label: "Duration",
        type: "slider",
        description: "Generated clip length in seconds",
        required: false,
        defaultValue: "11",
        options: null,
        min: 2,
        max: 15,
        accept: null,
      },
      {
        key: "resolution",
        label: "Resolution",
        type: "select",
        description: "Hosted video output resolution",
        required: false,
        defaultValue: "720p",
        options: ["480p", "720p", "1080p"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "generate_audio",
        label: "Generated Audio",
        type: "select",
        description: "Let Seedance generate and mix sound alongside the reference audio",
        required: false,
        defaultValue: "true",
        options: ["true", "false"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "perform-anywhere-seedance",
    name: "Perform Anywhere — Seedance API",
    description:
      "Upload a selected cinematic still and your phone performance recording to ModelArk's hosted Seedance video API. No local ComfyUI GPU is used for the motion stage.",
    category: "perform-anywhere",
    icon: "Sparkles",
    estimatedTime: "1-5 min",
    params: [
      {
        key: "source_image",
        label: "Selected Angle",
        type: "file",
        description: "The generated angle you selected",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "source_video",
        label: "Performance Video",
        type: "file",
        description: "The movement reference to transfer to the selected still",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "video/*",
      },
      {
        key: "motion_context",
        label: "Motion Context",
        type: "text",
        description: "Describe the action and visual continuity",
        required: true,
        defaultValue: "Transfer the performance naturally while preserving the reference scene.",
        options: null,
        min: null,
        max: 500,
        accept: null,
      },
      {
        key: "model",
        label: "Seedance Model",
        type: "text",
        description: "ModelArk model or endpoint ID",
        required: false,
        defaultValue: "dreamina-seedance-2-5-260628",
        options: null,
        min: null,
        max: 120,
        accept: null,
      },
      {
        key: "resolution",
        label: "Resolution",
        type: "select",
        description: "Hosted video output resolution",
        required: false,
        defaultValue: "720p",
        options: ["480p", "720p", "1080p"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "ratio",
        label: "Aspect Ratio",
        type: "select",
        description: "Hosted video composition",
        required: false,
        defaultValue: "16:9",
        options: ["16:9", "9:16", "1:1"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "modelark-seedream-image",
    name: "Seedream Image",
    description:
      "Generate an image directly through ModelArk Seedream without using a local ComfyUI GPU.",
    category: "image-generation",
    icon: "Image",
    estimatedTime: "10-60 sec",
    params: [
      {
        key: "prompt",
        label: "Image Direction",
        type: "text",
        description: "Describe the image, subject, composition, lighting, and style.",
        required: true,
        defaultValue: "A cinematic editorial portrait in a rain-soaked neon city at night",
        options: null,
        min: 1,
        max: 6000,
        accept: null,
      },
      {
        key: "model",
        label: "Seedream Model",
        type: "select",
        description: "Choose the hosted ModelArk image model.",
        required: false,
        defaultValue: "dola-seedream-5-0-pro-260628",
        options: [
          "dola-seedream-5-0-pro-260628",
          "seedream-5-0-lite-260128",
          "seedream-5-0-260128",
          "seedream-4-5-251128",
          "seedream-4-0-250828",
        ],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "size",
        label: "Resolution",
        type: "select",
        description: "ModelArk image resolution tier.",
        required: false,
        defaultValue: "2K",
        options: ["1K", "1.5K", "2K", "auto"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "n",
        label: "Variations",
        type: "slider",
        description: "Number of hosted image variations to create.",
        required: false,
        defaultValue: "1",
        options: null,
        min: 1,
        max: 4,
        accept: null,
      },
    ],
  },
  {
    id: "perform-anywhere-motion",
    name: "Perform Anywhere — Animate Selected Angle",
    description:
      "Drive a selected cinematic still with your original performance video using MimicMotion.",
    category: "perform-anywhere",
    icon: "Video",
    estimatedTime: "4-12 min",
    params: [
      {
        key: "source_image",
        label: "Selected Angle",
        type: "file",
        description: "The generated angle you selected",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "performance_video",
        label: "Performance Video",
        type: "file",
        description: "Your original phone recording with matching framing and position",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "video/*",
      },
      {
        key: "motion_context",
        label: "Motion Context",
        type: "text",
        description: "Describe what is happening to help prevent scene artifacts",
        required: true,
        defaultValue: "a performer moving naturally inside the scene",
        options: null,
        min: null,
        max: 300,
        accept: null,
      },
      {
        key: "num_frames",
        label: "Frames",
        type: "slider",
        description: "Longer clips require more GPU memory",
        required: false,
        defaultValue: "48",
        options: null,
        min: 16,
        max: 72,
        accept: null,
      },
    ],
  },
  {
    id: "custom-workflow",
    name: "Custom Workflow",
    description:
      "Paste your own ComfyUI API-format workflow JSON and run it directly — supports any nodes or extensions installed on your server.",
    category: "custom",
    icon: "Code",
    estimatedTime: "varies",
    params: [
      {
        key: "workflow_json",
        label: "Workflow JSON",
        type: "text",
        description: "Paste your ComfyUI API-format workflow JSON here (export from ComfyUI with 'Save (API format)')",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: 999999,
        accept: null,
      },
    ],
  },
  {
    id: "img2vid-stable-video",
    name: "Image to Video",
    description:
      "Convert a still image into a short animated video clip using Stable Video Diffusion.",
    category: "video-generation",
    icon: "Film",
    estimatedTime: "3-10 min",
    params: [
      {
        key: "source_image",
        label: "Source Image",
        type: "file",
        description: "The image to animate into video",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "motion_bucket_id",
        label: "Motion Amount",
        type: "slider",
        description: "Controls how much the scene moves (1 = subtle, 255 = heavy motion)",
        required: false,
        defaultValue: "127",
        options: null,
        min: 1,
        max: 255,
        accept: null,
      },
      {
        key: "fps",
        label: "Frames Per Second",
        type: "select",
        description: "Output video frame rate",
        required: false,
        defaultValue: "6",
        options: ["6", "8", "12", "24"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "num_frames",
        label: "Number of Frames",
        type: "select",
        description: "Total frames in the video",
        required: false,
        defaultValue: "25",
        options: ["14", "25"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  // ─── Cinematic ───────────────────────────────────────────────
  {
    id: "cinematic-film-grade",
    name: "Film Grain & Color Grade",
    description:
      "Give any video a cinematic look — teal-orange color grade, film grain, and vignette applied to your uploaded footage.",
    category: "cinematic",
    icon: "Clapperboard",
    estimatedTime: "2-6 min",
    params: [
      {
        key: "source_video",
        label: "Source Video",
        type: "file",
        description: "The video clip to grade (MP4 works best)",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "video/*",
      },
      {
        key: "grain_power",
        label: "Grain Intensity",
        type: "slider",
        description: "How visible the film grain is (0-100)",
        required: false,
        defaultValue: "60",
        options: null,
        min: 0,
        max: 100,
        accept: null,
      },
      {
        key: "grade_style",
        label: "Grade Style",
        type: "select",
        description: "The color grading look to apply",
        required: false,
        defaultValue: "teal-orange",
        options: ["teal-orange", "warm-vintage", "cold-thriller", "bleach-bypass"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "cinematic-portrait",
    name: "Cinematic Portrait",
    description:
      "Generate a movie-still portrait with shallow depth of field and creamy bokeh — like an 85mm lens at golden hour.",
    category: "cinematic",
    icon: "Aperture",
    estimatedTime: "1-3 min",
    params: [
      {
        key: "prompt",
        label: "Subject Description",
        type: "text",
        description: "Describe the person and scene (e.g. 'a violinist on a rainy rooftop at dusk')",
        required: true,
        defaultValue: "",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "bokeh_strength",
        label: "Bokeh Strength",
        type: "slider",
        description: "How blurred the background is (0-100)",
        required: false,
        defaultValue: "70",
        options: null,
        min: 0,
        max: 100,
        accept: null,
      },
      {
        key: "lighting",
        label: "Lighting Style",
        type: "select",
        description: "The mood of the light",
        required: false,
        defaultValue: "golden-hour",
        options: ["golden-hour", "neon-night", "soft-window", "dramatic-rim"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "cinematic-slowmo-upscale",
    name: "Slow-Motion Upscale",
    description:
      "Turn ordinary footage into buttery slow motion — AI frame interpolation (RIFE) plus 2x upscaling for crisp results.",
    category: "cinematic",
    icon: "Timer",
    estimatedTime: "5-15 min",
    params: [
      {
        key: "source_video",
        label: "Source Video",
        type: "file",
        description: "The video clip to slow down",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "video/*",
      },
      {
        key: "slowdown_factor",
        label: "Slowdown Factor",
        type: "select",
        description: "How many extra frames to generate (4x = quarter speed)",
        required: false,
        defaultValue: "4",
        options: ["2", "4", "8"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "upscale",
        label: "Upscale Output",
        type: "select",
        description: "Sharpen and enlarge the result",
        required: false,
        defaultValue: "2x",
        options: ["none", "2x"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "cinematic-epic-landscape",
    name: "Epic Landscape",
    description:
      "Generate vast wide-angle landscapes with dramatic skies — automatic sky detection and enhancement for epic scale.",
    category: "cinematic",
    icon: "Mountain",
    estimatedTime: "2-4 min",
    params: [
      {
        key: "prompt",
        label: "Landscape Description",
        type: "text",
        description: "Describe the scene (e.g. 'volcanic coastline under a violet aurora')",
        required: true,
        defaultValue: "",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "sky_style",
        label: "Sky Style",
        type: "select",
        description: "The type of dramatic sky",
        required: false,
        defaultValue: "storm-god-rays",
        options: ["storm-god-rays", "sunset-fire", "aurora-night", "clear-alpine"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "aspect",
        label: "Aspect Ratio",
        type: "select",
        description: "Output shape",
        required: false,
        defaultValue: "16:9",
        options: ["16:9", "21:9", "3:2"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  // ─── Content creation ────────────────────────────────────────
  {
    id: "content-reel-loop",
    name: "Instagram Reel Loop",
    description:
      "Create a seamless looping short video in vertical format — perfect for Reels, TikTok, and Shorts backgrounds.",
    category: "content-creation",
    icon: "Repeat",
    estimatedTime: "4-10 min",
    params: [
      {
        key: "prompt",
        label: "Loop Description",
        type: "text",
        description: "Describe the looping visual (e.g. 'liquid gold waves flowing endlessly')",
        required: true,
        defaultValue: "",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "duration",
        label: "Loop Length",
        type: "select",
        description: "Length of one loop cycle in seconds",
        required: false,
        defaultValue: "2",
        options: ["2", "4", "6"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "style",
        label: "Visual Style",
        type: "select",
        description: "The overall aesthetic",
        required: false,
        defaultValue: "neon-abstract",
        options: ["neon-abstract", "nature-calm", "retro-vhs", "minimal-gradient"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "content-product-swap",
    name: "Product Background Swap",
    description:
      "Upload a product photo and swap the background for a clean studio scene — automatic product masking included.",
    category: "content-creation",
    icon: "Package",
    estimatedTime: "1-3 min",
    params: [
      {
        key: "product_image",
        label: "Product Photo",
        type: "file",
        description: "A photo of your product (any background)",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "background_prompt",
        label: "New Background",
        type: "text",
        description: "Describe the backdrop (e.g. 'marble pedestal with soft studio lighting')",
        required: true,
        defaultValue: "clean minimal studio backdrop, soft shadows",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
  {
    id: "content-talking-avatar",
    name: "Talking Avatar",
    description:
      "Turn a portrait photo plus a voice recording into a talking-head video — great for faceless channels and explainers.",
    category: "content-creation",
    icon: "UserRound",
    estimatedTime: "3-8 min",
    params: [
      {
        key: "portrait_image",
        label: "Portrait Photo",
        type: "file",
        description: "A clear front-facing portrait",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "image/*",
      },
      {
        key: "speech_audio",
        label: "Speech Audio",
        type: "file",
        description: "The voice track to speak (WAV or MP3)",
        required: true,
        defaultValue: null,
        options: null,
        min: null,
        max: null,
        accept: "audio/*",
      },
      {
        key: "expression_scale",
        label: "Expressiveness",
        type: "slider",
        description: "How animated the face is (0-100)",
        required: false,
        defaultValue: "50",
        options: null,
        min: 0,
        max: 100,
        accept: null,
      },
    ],
  },
  {
    id: "content-blog-hero",
    name: "Blog Hero Image",
    description:
      "Generate wide hero images with space for headline text — consistent brand-style illustrations for articles and newsletters.",
    category: "content-creation",
    icon: "Newspaper",
    estimatedTime: "1-2 min",
    params: [
      {
        key: "prompt",
        label: "Article Topic",
        type: "text",
        description: "What the article is about (e.g. 'remote work productivity tips')",
        required: true,
        defaultValue: "",
        options: null,
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "brand_style",
        label: "Brand Style",
        type: "select",
        description: "The illustration aesthetic",
        required: false,
        defaultValue: "flat-pastel",
        options: ["flat-pastel", "bold-editorial", "soft-3d", "line-art"],
        min: null,
        max: null,
        accept: null,
      },
      {
        key: "text_space",
        label: "Headline Space",
        type: "select",
        description: "Where to leave empty space for your headline",
        required: false,
        defaultValue: "left",
        options: ["left", "right", "center", "none"],
        min: null,
        max: null,
        accept: null,
      },
    ],
  },
];

router.get("/workflows", async (_req, res): Promise<void> => {
  res.json(ListWorkflowsResponse.parse(WORKFLOWS));
});

router.get("/workflows/:id", async (req, res): Promise<void> => {
  const params = GetWorkflowParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const workflow = WORKFLOWS.find((w) => w.id === params.data.id);
  if (!workflow) {
    res.status(404).json({ error: "Workflow not found" });
    return;
  }

  res.json(GetWorkflowResponse.parse(workflow));
});

export { WORKFLOWS };
export default router;
